### ISSUE TITLE
Targeting .NET 7 on macOS 13 throws PlatformNotSupportedException

### ISSUE THREAD

**Issue by PedroCavaleiro** [nozomi-ai/websocket-sharp#5]
Using the 1.0.1-alpha.4 version of this lib on macOS 13 targeting .NET 7 throws `PlatformNotSupportedException`

I don't have much more information on this error
`Exception thrown: 'System.PlatformNotSupportedException' in websocket-sharp.dll`

**Comment by Robertsmania** [comment]
Were you seeing this with the WebSocket (client) or WebSocketServer class?

**Comment by PedroCavaleiro** [comment]
Since I was having issues and received no reply I moved away from this library, that and I no longer use macOS 13

However this was on the WebSocketServer.

**Comment by Robertsmania** [comment]
Thank you for the reply anyway.  I'm struggling to find a good web socket server for a C# .NET 7 project.  We had been using the normal WebSocketSharp in the older version which was .NET Framework 4.7.2 but in the new stuff we see the same PlatformNotSupportedException.

Did you find a satisfactory Web Socket Server library?

**Comment by PedroCavaleiro** [comment]
For now this is the one that I have working without issues 

[VIEApps.Components.WebSockets ](https://www.nuget.org/packages/VIEApps.Components.WebSockets)
